name: outgoing-proxy
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

aws:
  region: ""
  azs: []

apps:
  cilliumApiEndpoint: ""
  # used by renovate
  # repo: giantswarm/default-apps-aws
  version: "0.30.0"

cluster:
  baseDomain: ""
  dnsMode: "public"
  name: outgoing-proxy
  vpcCIDR: 10.255.0.0/16
  organization: giantswarm
  # used by renovate
  # repo: giantswarm/cluster-aws
  version: "0.36.2"

proxy:
  # used by renovate
  # repo: giantswarm/squid-proxy-app
  version: "0.3.1"
  image: giantswarm/squid
  tag: 5.2-22.04_beta-giantswarm
