apiVersion: v1
data:
  values: |
    aws: {}
    bastion: 
      enabled: false
    clusterName: {{ .Values.cluster.name }}
    proxy:
      enabled: false
    controlPlane:
      replicas: 1
    machinePools:
    - instanceType: m5.xlarge
      maxSize: 2
      minSize: 2
      name: machine-pool0
      rootVolumeSizeGB: 100
    network:
      availabilityZoneUsageLimit: 3
    organization: {{ .Values.cluster.organization }}
kind: ConfigMap
metadata:
  labels:
    giantswarm.io/cluster: {{ .Values.cluster.name }}
  name: {{ .Values.cluster.name }}-userconfig
  namespace: {{ $.Release.Namespace }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "yes"
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ .Values.cluster.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: cluster
  name: cluster-aws
  namespace: {{ $.Release.Namespace }}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  userConfig:
    configMap:
      name: {{ .Values.cluster.name }}-userconfig
      namespace: {{ $.Release.Namespace }}
  version: {{ .Values.cluster.version }}
---
apiVersion: v1
data:
  values: |
    clusterName: {{ .Values.cluster.name }}
    organization: {{ .Values.cluster.organization }}
kind: ConfigMap
metadata:
  labels:
    giantswarm.io/cluster: {{ .Values.cluster.name }}
  name: {{ .Values.cluster.name }}-default-apps-userconfig
  namespace: {{ $.Release.Namespace }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
  name: {{ .Values.cluster.name }}-default-apps
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: cluster
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: default-apps-aws
  namespace: {{ $.Release.Namespace }}
  userConfig:
    configMap:
      name: {{ .Values.cluster.name }}-default-apps-userconfig
      namespace: {{ $.Release.Namespace }}
  version: {{ .Values.apps.version }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "false"
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: squid-proxy-app
    giantswarm.io/cluster: {{ .Values.cluster.name }}
    giantswarm.io/service-type: managed
  name: {{ .Values.cluster.name }}-squid
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: giantswarm-playground
  kubeConfig:
    context:
      name: {{ .Values.cluster.name }}-admin@{{ .Values.cluster.name }}
    inCluster: false
    secret:
      name: {{ .Values.cluster.name }}-kubeconfig
      namespace: {{ $.Release.Namespace }}
  name: squid-proxy
  namespace: kube-system
  version: {{ .Values.proxy.version }}
